//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MakeInstall.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MakeInstall.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///	&quot;Name&quot;: &quot;example&quot;,
        ///	&quot;Start&quot;: &quot;example.exe&quot;,
        ///	&quot;Source&quot;: &quot;path/to/contain/example/&quot;,
        ///	&quot;Filter&quot;: [ &quot;.exe&quot;, &quot;.dll&quot; ],
        ///	&quot;DesktopIcon&quot;: true,
        ///	&quot;StartScreen&quot;: true,
        ///	&quot;InstallFolder&quot;: &quot;C:\\Program Files&quot;,
        ///	&quot;OverrideExists&quot;: true,
        ///	&quot;Output&quot;: &quot;example-installer.exe&quot;,
        ///	&quot;RegValues&quot;: [
        ///		{
        ///			&quot;Type&quot;: &quot;HKEY_LOCAL_MACHINE&quot;,
        ///			&quot;Path&quot;: &quot;SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall&quot;,
        ///			&quot;Name&quot;: &quot;example&quot;,
        ///			&quot;Values&quot;: {
        ///				&quot;DisplayIcon&quot;: &quot;${install_path}\\example.exe&quot;,
        ///				&quot;InstallLocation&quot;:&quot; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string pack_example {
            get {
                return ResourceManager.GetString("pack_example", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 -----BEGIN RSA PRIVATE KEY-----
        ///MIICXAIBAAKBgQCtuh2Oajk9Nufz6DLXH1xpsBmWrFAIJ41s3QapRDfFM19FPOui
        ///msBDXni5gQ4AGVrnS0LmKjdqgvOLDluZnc9bgnfHQDzwPnuO6WSpVdXTG2D8lM0u
        ///AYkN9xRAXkcYzwt1GzNGPJuwBF/cFCGcMXjcVgmVc+KKeorsieopuSudAQIDAQAB
        ///AoGAM90FJ9gEYIb8ti8SxnAhWZft+7JTbivIp8BQVcX81E1i2ru2KOQEE9inN9IU
        ///SOlI3xXz0dy2kICpjlDp/bFEDrKpjQgJEiqdMsjM+4cU4cwdbFkzMHLHu+StDq+y
        ///UeRKPXuHvZyLmeEB+7ruqyjZ8A25YCaWg8f1A6tyWBrGd7UCQQDZdVYIarsIE8hU
        ///mDdhBqpWxmecOBfF87kosV4gmQszIulWkUyiEFS3bzYHxpK4lQ1M1V13NY6ubSdg
        ///9s2YPpXfAkEAzISSkCCvxFRC6 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string rsa_private_key {
            get {
                return ResourceManager.GetString("rsa_private_key", resourceCulture);
            }
        }
    }
}
